#!/bin/sh

set -eu

# Options
#   --commands  show all commands and exit.
#   --default   show commands that will run by default and exit.
#   --run       forces a command to be run and be installed in the system even if does not default.

main() {
  cd "$(dirname "$0")"; SETUP="${PWD}"; export SETUP
  script="${0##*/}"; export SCRIPT_D="${SETUP}/${script}.d"
  export PATH="${SCRIPT_D}/utils:${PATH}"
  
  for arg; do
    case "${arg}" in
      --default) to --scripts | sh -s "${arg}"; exit ;;
      --dry-run) export DRY_RUN=1 ;;
      --run) run="${arg}" ;;
      *) set -- "${arg}" "$@"
    esac
    shift
  done
  
  commands="$(to --default)"
  # TODO: aqui lo dejo -  ... falta el ver el resumen del --run 
  if [ "$#" -eq 0 ]; then 
    [ ! "${run-}" ] || commands="$(to "${arg}")"
  else
    echo "$@" | grep b
  fi
}

main "$@"
