#!/bin/sh

set -eu

main() {
  cd "$(dirname "$0")"; SETUP="${PWD}"; export SETUP
  script="${0##*/}"; export SCRIPT_D="${SETUP}/${script}.d"
  export PATH="${SCRIPT_D}/utils:${PATH}"

  for arg; do
    case "${arg}" in
      --commands) to --scripts | sh -s --commands; exit ;;
    esac
  done
}

main "$@"
