#!/bin/sh

#
# run pull/pull if needed or exit with error if diverged

set -eu 

command() {
  if [ "${LOCAL}" != "${REMOTE}" ]; then
    git fetch --quiet 
    base=$(git merge-base @ @{u})
    if [ "${LOCAL}" = "${base}" ]; then
      echo "git pull"
    elif [ "${REMOTE}" = "${base}" ]; then
      echo "git push"
    else
      echo "Diverged" >&2  # Different commits in both local and remote
      exit 1
    fi
  fi
}

# @     current local branch
# @{u}  its upstream branch

LOCAL="$(git rev-parse @)"
REMOTE="$(git ls-remote origin HEAD | awk '{ print $1 }')"  # HEAD or @, git fetch if there are changes, or:
# REMOTE=$(git rev-parse @{u})

if [ "${1-}" = '--dry-run' ]; then
  command
else 
  $(command)
fi
