#!/bin/sh

# 
# scripts to commands and viceversa

set -eu

commands () { sed -e 's|^.*[0-9][0-9]-||g; s|.sh||g'; }
scripts() { find "${SCRIPT_D}" -maxdepth 1 -type f -name ??-*.sh -exec basename "{}" \;; }

# Examples:
#   to --commands
#   to --scripts
#   to --command="90-jetbrains copy.sh"
#   to --script=jetbrains
#   printf '%s\n' 90-jetbrains.sh '90-jetbrains copy.sh' | xargs -I {} to --command="{}"
#   printf '%s\n' jetbrains 'jetbrains copy' | xargs -I {} to --script="{}"
  
main() {
  for arg; do
    case "${arg}" in
      --commands) scripts | commands ;;
      --scripts) scripts ;;
      --command=*) echo "${arg#--command=}" | commands ;;
      --script=*) scripts | grep "^[0-9][0-9]-${arg#--script=}.sh" ;;
    esac
  done
}

main "$@"
